### ISSUE TITLE
题库又更新啦大佬

### ISSUE THREAD

**Issue by Cathjoe** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#13]

**Comment by MlgmXyysd** [comment]
已知，正在整理。但因小米最近的改动（不再对5级以下的号登记和展示得分），无法再确定题目**在小米那边**的正确答案是什么（已知小米曾出过答案出错/不合理/与现有文档不符，误导用户的题目/选项），不再能保证所给答案为**满分**答案

**Comment by MlgmXyysd** [comment]
已更新
