### ISSUE TITLE
答题结束后显示您的成绩不存在

### ISSUE THREAD

**Issue by Boom-Hacker** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#207]

**Comment by xbn2002** [comment]
有几种可能的情况：
1. 提交的时候没有满 10 分钟；
2. 过了 08:15 才提交。

**Comment by Boom-Hacker** [comment]
这种情况需要等七天再答吗 明天还有一场

**Comment by yatokk** [comment]
能用无线调试来答题吗

**Comment by Boom-Hacker** [comment]
> > 这种情况需要等七天再答吗 明天还有一场
> 
> 你看下答题那边有没有 再次答题 的按钮就知道了

今天早上我进不去 显示没开 是临时取消了吗

**Comment by xbn2002** [comment]
> > > 这种情况需要等七天再答吗 明天还有一场
> > 
> > 
> > 你看下答题那边有没有 再次答题 的按钮就知道了
> 
> 今天早上我进不去 显示没开 是临时取消了吗

昨天是临时改时间，最近这种情况很常见，经常临时改，米米耍猴呢
