### ISSUE TITLE
## 温馨提示

### ISSUE THREAD

**Issue by 2628567306** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#212]
## 温馨提示
题库版本：2024.07.25
**使用浏览器搜索题目中特征明显的关键字**，即可搜索相应题目
题目表述经常有细微变化，**答题时建议不要直接搜索整个选项**
本题库解析 @MlgmXyysd @xbn2002 @Edwin-Kevin 版权所有，转载请注明出处

## 目录
- [公告题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8631884)
- [单选题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8638756)
- [多选题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8638772)
- [判断题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8638782)
- [填空题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8639323)
- [截图题](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95#discussioncomment-8639324)

_Originally posted by @xbn2002 in https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/95_

**Comment by xiaoboluoya** [comment]
解除BL锁的危害
