### ISSUE TITLE
这道题目有点不严谨

### ISSUE THREAD

**Issue by yunyechen** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#226]
这个真的是小米官方的题目吗，还是你弄错了，非MTK那麒麟应该也算吧，麒麟难道有9008？
![IMG_20241101_212734](https://github.com/user-attachments/assets/fdfa43fc-981e-43da-bf07-db2ed613e727)

**Comment by xbn2002** [comment]
小米官方的题目本来就很不严谨，很多题目模棱两可。对于这一类题目，小米那边的答案就需要靠很多5级号来“试验”，通过对答案进行猜测并观察分数来确定。题目的解析也只能根据小米的观点来写。

**Comment by xbn2002** [comment]
另外，这个网站的内容已经过时很久了。最后的更新时间还是今年1月。最新的题目请以本仓库的discussion置顶帖为准。
