### ISSUE TITLE
超时不会显示分数了

### ISSUE THREAD

**Issue by Jonah-77** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#23]
规则似乎又改了，现在超时并不会结算已回答的分数了![Screenshot_2023-12-21-13-15-26-922_com.xiaomi.vipaccount.jpg](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/assets/59916652/915c2f0c-8159-430d-a893-5056915f6062)

**Comment by MlgmXyysd** [comment]
看起来和之前一样

**Comment by Jonah-77** [comment]
> 看起来和之前一样

大佬你看第一段的第三条

**Comment by MlgmXyysd** [comment]
> > 看起来和之前一样
> 
> 大佬你看第一段的第三条

结算是意思是按当前回答的问题提交答卷，不能再重复作答，分数在后台记录
跳转回到社区不到5级显示无效答卷
好几天前就已经改成这样了

**Comment by Jonah-77** [comment]
> > > 看起来和之前一样
> > 
> > 大佬你看第一段的第三条
> 
> 结算是意思是按当前回答的问题提交答卷，不能再重复作答，分数在后台记录
> 跳转回到社区不到5级显示无效答卷
> 好几天前就已经改成这样了

他后台记录我5级了也不给我显示分数也不让通过，可恶的小米啊啊啊

**Comment by MlgmXyysd** [comment]
> > > > 看起来和之前一样
> > > 
> > > 
> > > 大佬你看第一段的第三条
> > 
> > 
> > 结算是意思是按当前回答的问题提交答卷，不能再重复作答，分数在后台记录
> > 跳转回到社区不到5级显示无效答卷
> > 好几天前就已经改成这样了
> 
> 他后台记录我5级了也不给我显示分数也不让通过，可恶的小米啊啊啊

故意的，小蜜蜂那边有分数，就是不给同步
