### ISSUE TITLE
题目1508241的答案疑似有误

### ISSUE THREAD

**Issue by zhouym233** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#28]
1508241 以下说法**不正确**的有 【多选题】
4948296 Android系统启动时，首先启动的是zygote进程
❌ 不选。Zygote 进程由 Android 运行时（Android Runtime, ART）启动。所以第一个启动的进程并不是 Zygote。

**Comment by MlgmXyysd** [comment]
已知
https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/discussions/27
