### ISSUE TITLE
题目更新了

### ISSUE THREAD

**Issue by Xisen-XJX** [MlgmXyysd/Xiaomi-BootLoader-Questionnaire#9]
![Screenshot_2023-12-11-21-04-55-463_com android browser](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/assets/139407912/34ae9019-2857-40fd-8460-86eb09a79915)
![Screenshot_2023-12-11-21-04-24-404_com android browser](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/assets/139407912/daa06432-bea9-4011-8178-cbf7d8df49f1)
![Screenshot_2023-12-11-21-02-41-686_com android browser](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/assets/139407912/d5805b17-6f6f-4969-a035-6b5252d19ba1)
![Screenshot_2023-12-11-21-00-39-247_com android browser](https://github.com/MlgmXyysd/Xiaomi-BootLoader-Questionnaire/assets/139407912/41b5e633-5f1a-4d40-993b-ba7fbba73983)

**Comment by MlgmXyysd** [comment]
已更新
